# Generated by Django 3.0.8 on 2020-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
