# Generated by Django 3.0.8 on 2020-07-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body',
            new_name='team_title',
        ),
    ]
