# Generated by Django 3.0.8 on 2020-07-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicespage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio_images',
            old_name='pitch',
            new_name='lawyer_description',
        ),
        migrations.RenameField(
            model_name='portfolio_images',
            old_name='tag',
            new_name='lawyer_title',
        ),
    ]
